### ISSUE TITLE
Hang on click of Done button after selecting images

### ISSUE THREAD

**Issue by karthikmandava7** [opalorange/OpalImagePicker#51]
After selecting images. I'm clicking on Done button and then it hangs for 2 or 3 seconds.

**Comment by parrotbait** [comment]
Yes, this library should show a loading indicator as it downloads the images from the cloud - that's the issue with the hang.

**Comment by kingsofteng** [comment]
Instead of hanging, you can just use the asynchronous downloading and can show loading indicators for the cells.

**Comment by opalorange** [comment]
Thanks for bringing this to my attention. I am deprecating the `selectImages` closure and delegate function in the next version. Instead of working with `UIImage`, I think it makes more sense for the users of the library to download their desired resolution from the cloud using the `selectAssets` and `PHAsset` and show a loading indicator after the picker has been dismissed.
