### ISSUE TITLE
Enabling 'Done' when no photos are selected || all photos are deselected

### ISSUE THREAD

**Issue by datureezy** [opalorange/OpalImagePicker#7]
Hello Kristos!

Very nice Image Picker solution you've built for the world :)

Is there a particular reason as to why you have disabled the 'Done' button on your image picker when there are zero photos selected? I select photos, press done, it closes. But if I go back to the image picker, deselect the photos, I'm unable to press done. I see you're updating the done button's enabling on didSelectItemAt & didDeselectItemAt...

I would think that when you press Done -> It submits your changes and actions... 
ex: Selection from 0 photos to 1 photo, saves with Done.
ex: Selection from 1 photo to 0 photos, saves with Done.

And when you press Cancel -> It doesn't submit any changes and actions you may have taken.
ex: Open with 0 photos, cancel, ending with 0 photos.
ex. Open with 1 photos, select 1 photo, cancel, end with 1 photo.
ex. Open with 0 photos, select 1 photo, cancel, end with 0 photos.

What do you think? If you're okay with me making these changes, I'll send in a pull request.

Ron

**Comment by opalorange** [comment]
Hi Ron,
Thanks for the comment. I like your input, I think this is something I overlooked when I was building the component. Go ahead and make a pull request, and I will review it.

One note, when you are working on this change, please make sure to call the `imagePickerDidCancel(_:)` rather than `imagePicker(_:didFinishPickingAssets)` on the delegate. This needs to happen when you press the "Done" button with 0 images selected, otherwise it could mess up the logic people have built into their apps.
